### ISSUE TITLE
Xcode project? Version 8?

### ISSUE THREAD

**Issue by EddyLB** [IP-XOP/SOCKIT#2]
I would like to prepare a signed version for Igor Pro 8, which would take a few minutes, but I see that the Xcode project is not available and that the version of this XOP for IP8 was not released. Could you please commit the Xcode project and produce the release? That would be greatly appreciated.

**Comment by andyfaff** [comment]
I'd find it interesting to find out more about code signing. It's going to cause a lot of work because I have so many different projects.

I've made a tag for IP8 (although I don't think the code itself has changed), made a release with the IP8 SOCKIT binary and also the archived Xcode project as it exists on my computer. It doesn't seem to me that Xcode projects are particularly amenable to being added to a git tree.

If you're interested in coming on board to help develop any of my XOPs you'd be more than welcome, it'd really help me out.

**Comment by EddyLB** [comment]
With pleasure. Please add me to IP-XOP ;-) 
We use your SOCKIT and XMLutils XOPs at our lab. I will sign them so that Wavemetrics can distribute them if that helps.

**Comment by andyfaff** [comment]
I'm happy to add you as a contributor, allowing you to merge code, make releases, etc. COuld I suggest the following ground rules:

- all code added goes through a PR to get visibility
- PRs get made on a feature branch, not on the main branch
- a reasonable coding style is adhered to (this C code is way back from when I was very inexperienced as a programmer)

**Comment by EddyLB** [comment]
Perfect. This is the way I use to work.
